import 'package:connectivity_plus/connectivity_plus.dart';
import 'package:get_it/get_it.dart';
import 'package:injectable/injectable.dart';

import 'injection.config.dart'; // from injectable

final sl = GetIt.instance;

@InjectableInit()
Future<void> configureDependencies() async {
  sl.registerLazySingleton<Connectivity>(() => Connectivity());
  sl.init(); // generated by `injectable`
}
